### ISSUE TITLE
Simple installation using straight and emacs 29

### ISSUE THREAD

**Issue by dleslie** [sogaiu/flycheck-janet#1]
```
 (use-package flycheck-janet
    :straight (:type git :host github :repo "sogaiu/flycheck-janet" :files ("*.el")))
```

That should be all that's needed to install it.

**Comment by sogaiu** [comment]
_Update_: Earlier content was confused.  Hopefully what's below makes more sense (^^;

I used to use lines close to [these](https://github.com/sogaiu/janet-emacs-trial-kit/blob/3f097ad38d9a3e586285572eb311751b0993ce5c/init.el#L217-L224):

```elisp
(straight-use-package
 '(flycheck-janet :host github
                  :repo "sogaiu/flycheck-janet"
                  :files ("*.el")))

(use-package flycheck-janet
  :straight t)
```

What you posted looks more concise.  May be it would have worked for me too.

BTW, is the intention of this issue to suggest addition of instructions for setup with straight.el to the README?

I stopped using straight.el [1] so I don't tend to test with it any more.

---

[1] I have moved to elpaca which seems to be worked on by a co-maintainer of straight.el.  I'm hoping to just use built-in stuff in Emacs eventually but that doesn't seem ready yet.
